# Generated by Django 4.2.1 on 2024-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
