# Generated by Django 4.2.1 on 2024-03-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drive_File',
        ),
    ]
