# Generated by Django 4.2.1 on 2024-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='extenstion',
            new_name='extension',
        ),
    ]
