# Generated by Django 4.2.1 on 2024-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_drive_file_file_alter_email_file_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive_file',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\mail_drive\\project\\static\\media'),
        ),
        migrations.AlterField(
            model_name='email_file',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\mail_drive\\project\\static\\media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\mbaji\\Desktop\\Django Projects\\mail_drive\\project\\static\\media'),
        ),
    ]
