# Generated by Django 4.2.1 on 2024-04-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drive_file',
            options={'ordering': ['-timestamp']},
        ),
    ]
