# Generated by Django 4.2.1 on 2024-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drive_file',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='drive_file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='email_file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
