# Generated by Django 4.2.1 on 2024-04-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_drive_file_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_file',
            name='email',
        ),
        migrations.AddField(
            model_name='email_file',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.email'),
        ),
    ]
