# Generated by Django 4.2.1 on 2024-04-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_email_file_email_email_file_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_file',
            name='email',
        ),
        migrations.AddField(
            model_name='email',
            name='files',
            field=models.ManyToManyField(blank=True, to='core.email_file'),
        ),
    ]
