# Generated by Django 4.2.1 on 2024-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_email_file_email_email_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='files',
        ),
        migrations.AddField(
            model_name='email_file',
            name='email',
            field=models.ManyToManyField(related_name='files', to='core.email'),
        ),
    ]
