# Generated by Django 4.2.1 on 2024-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_drive_file_options_alter_drive_file_file_and_more'),
        ('core', '0023_remove_email_files_email_file_email'),
    ]

    operations = [
    ]
